### ISSUE TITLE
Error Handling in Data Queue

### ISSUE THREAD

**Issue by nathansamuell** [nathansamuell/groundStation#20]
If the app tries to read data and none has been received, it hangs and crashes on an error when the queue is empty. We need this error handled more gracefully!

Lulu and Sai -- we will work on this on Lab on thursday!

**Comment by shriy97** [comment]
> If the app tries to read data and none has been received, it hangs and crashes on an error when the queue is empty. We need this error handled more gracefully!
> 
> Lulu and Sai -- we will work on this on Lab on thursday!

Got it👍🏻

**Comment by nathansamuell** [comment]
Can't remember which commit/pull request we fixed this in but it's fixed!
